# Generated by Django 4.2.11 on 2024-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="code",
            field=models.TextField(blank=None, max_length=1000, null=None),
        ),
        migrations.AlterField(
            model_name="concept",
            name="describe",
            field=models.TextField(blank=None, max_length=1000, null=None),
        ),
    ]
