
services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: tutorial_prod_api
    container_name: tutorial_prod_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local  # docker compose -f local.yml config
    depends_on:
      - postgres
      - mailpit
      - redis
    command: /start
    networks:
      - tutorial_prod_nw  # docker network create tutorial_prod_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: tutorial_postgres
    container_name: tutorial_postgres
    ports:
      - "5432:5432"
    volumes:
      - tutorial_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - tutorial_prod_nw

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: estate_prod_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - tutorial_prod_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - tutorial_prod_nw

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    container_name: client
    image: client
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    # add this line(uncomment it) so that hot module reloading can work when working with windows subsystem for linux. 
    # environment:
    #   - WATCHPACK_POLLING=true
    networks:
      - tutorial_prod_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: estate_redis
    volumes:
      - tutorial_redis_prod_data:/data
    networks:
      - tutorial_prod_nw

  celeryworker:
    <<: *api
    image: tutorial_prod_celeryworker
    container_name: tutorial_prod_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *api
    image: tutorial_prod_celerybeat
    container_name: tutorial_prod_celerybeat
    command: /start-celerybeat

  flower:
    <<: *api
    image: tutorial_prod_flower
    container_name: tutorial_prod_flower
    ports:
      - "5555:5555"
    command: /start-flower

  
  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: tutorial_nginx
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - tutorial_prod_nw
    

networks:
  tutorial_prod_nw:
    external: true

volumes:
  tutorial_postgres_data: {}
  tutorial_prod_mailpit_data: {}
  logs_store: {}
  tutorial_redis_prod_data: {}


